

import React, {Component} from "react";
import { Link } from "react-router-dom";
import Navbar  from '../components/navbar';
import Footer  from '../components/footer';
import { Container, Row, Col, Button, Jumbotron } from 'reactstrap';
// import tempPic from '../images/p6.jpeg'

class Education extends Component {  

render() {
    return (
        <div>
            <Navbar/>
           <section id='education'>
                <Container id='educationCon'>
                <h1 className='blockHead'>Education in Powerlifting</h1>
                    <Container className='trainingBlock'>
                        <h5 className='eduText'>
                            As an engineering student at the University of Michigan, I seek measurable indicators of progression. Physical activity is no exception, so as an athlete that valued time invested in the weight room setting, the prospect of being able to quantify progression according to the amount of weight added to the bar seemed logical. Thus, started the journey of powerlifting for myself. Without much help, this journey began alone and as progression was made, I began to connect with individuals and meet people. However, many people close to me held very polarizing opinions about powerlifting and encouraged me to not partake due to the violent nature of it. In contrast, the more I immersed myself in the sport, the more I realized that a rage-filled approach wasn’t often rewarded. Having met several world-record-holding lifters, they all seemed to be calculated, precise, and methodical with their approach, this, however, extended far beyond the weight room. This realization has left me with a very specific question, is there a correlation between education success and powerlifting success?</h5>
                            <h5 className='eduText'>
                            As an elementary step, it seemed I should inquire about preconceived notions of powerlifters currently.  I went to a gym in Bay City, Michigan and asked fifteen people to identify the powerlifter based on the two pictures provided. One picture was of Russel Ohrii (one of the best powerlifters in the world as of this moment) and the other was Michelle Carter, a woman’s gold medal-winning shot putter. A large majority of the participants selected Michelle Carter as the powerlifter. This seemed to be no coincidence and the rationale that summarized the majority of the thought process was that Russel was too small to be an effective powerlifter, whereas Michelle Carter was a large human who appeared to be the better equipped individual to move the most amount of weight. This consensus led to the desire to represent the sport that powerlifting is while attempting to explain the role education plays in powerlifting.</h5>
                            <h5 className='eduText'>
                            Realizing the misconceptions that many people abide by, I decided to investigate the level of education that the best lifters in the world have received. The premier federations being the USPA (United States Powerlifting Association) and the USAPL (USA Powerlifting). These two federations make up most of the raw lifters (no squat suits, deadlift suits, or knee wraps) that compete. Raw lifting is the purest form of powerlifting as it based solely on the lifter’s ability to lift the weight. When one takes a cross-sectional analysis of the top ten lifters of each federation the results are nearly overwhelming. In the USAPL, five of the top ten lifters are college-educated, one of which graduated from Massachusetts Institute of Technology where he obtained a mechanical engineering degree. The idea of half or 50% of the top lifters in the USAPL being college-educated suggests that there is a correlation between education and powerlifting success. This correlation is supported by the fact that the premier lifters of the USAPL have a higher likelihood of being a college-educated individual than the national average, which is ⅓ of the American population according to Census: More Americans have college degrees than ever before by Reid Wilson.</h5>
                            <h5 className='eduText'>
                            While the USAPL might have a strong education presence, I believe it is worth examining other federations to confirm the previously suggested correlation in the USAPL. The other federation to be examined was the USPA. While researching the educational background of the top ten lifters in the USPA, I was able to conclude that 40% of the lifters had graduated from college and one of the lifters was currently pursuing a degree in education. Stephi Cohen possesses the highest degree of education which was a doctorate in physical therapy. This group exceeded the national average by 7% and could potentially exceed it by 17% if/when C.C. Ingram graduates. Both the USAPL and USPA outperformed the national average which leads to the desire to know why this trend is apparent in powerlifting.</h5>
                            <h5 className='eduText'>
                            To further understand the relationship between education and progression in powerlifting, I sought out a national qualifier in the USAPL and conducted an interview. This interviewee was able to qualify for USAPL nationals and in the process became very familiar with the intricacies of competition and powerlifting. The intent of the interview was to understand what exactly went into becoming a national competitor and if any of that success was attributable to education. The participant was quick to inform me that throughout his preparation for a competition, a lot of problems had presented themselves. The most notable to him were fatigue management and movement alteration. He went on to elaborate on both, saying this about fatigue management, “during my preparation for competition it progressively got harder to recover due to the fact I was continuously increasing volume in order to stimulate a compensation effect near the end of prep”. This seems unorthodox so further clarification was desired, and the participant continued on to explain that due to the body’s ability to recover, near the end of preparation, you want to push as hard as possible and nearly overtrain, then in the last week or two of training you then minimize the effort in the gym in order for the body to recuperate. This can help a lifter to be the strongest on the day of the meet. This nugget of information was something that few know but is certainly understandable.  When asked where this information was acquired from the participant had this to say, “When I was getting into this I found various forms of education on how to properly peak for a meet and across the board, all programs took heavy rep work a couple of weeks out with the purpose of exhausting oneself in order to then pull off the gas and let the body fully recover”. This seemed to suggest that there is a method for the programming a lifter receives in order to maximize their performance at their meet and while concluding this, it also seemed apparent that the interviewee possessed education outside of the realm of powerlifting. The diction and the way in which words were used was very precise while being observant of putting thoughts in palatable sentences in order to not lose the audience in his explanation. This tendency was very appreciable as it ensures that I was able to understand and utilize all the information he was attempting to convey.</h5>
                            <h5 className='eduText'>
                            In the preparation leading up to meets, it seems that most lifters are very calculated, and the interviewee suggested that this was incredibly common. To verify what was discussed in the interview, I researched some of the top lifters. One of the lifters that were very transparent with their approach to powerlifting was Sean Noriega. Sean documented his preparation leading up to Raw Nationals (the most competitive national level powerlifting competition) in which he highlighted the precision that leads to success, this came about in a YouTube video where he said, “... at the highest level of anything you’re attention to detail is everything”. Sean’s view on precision mirrored the way in which the interviewee was attentive to the word choice he used. Additionally, Sean discussed the rationale for training as the interviewee had suggested, as well as the science behind acquiring proper bloating and water manipulation for the meet. These seeming nuance details have been controlled and refined in order to give the best meet day performance and this was observed across all lifters at the top of the USAPL rankings. This supported what the interviewee had suggested and brought other details to light as well, it has seemed to be made apparent that in order to be able to perform as well as possible that things must be managed and calculated in order to toe the lines of too much and not enough. This attention to detail makes powerlifting a very accurate and precise sport.</h5>
                            <h5 className='eduText'>
                            While realizing the details and being attentive is one thing, it doesn’t necessarily demand a college education, so I discussed commonalities between the two with the interviewee, to gather further insight. When asked if education was necessary for progression the participant responded by saying, “a lifter either needs to be very educated [on powerlifting] and able to govern themselves which is probably the hardest, or a lifter needs a coach to tell them what to do and the coach needs to know how the lifter operates and what they respond best to. So yes, in short”.  This type of education is certainly important but still didn’t suggest a strong correlation to formal education, however with further questioning and conversation, it did become apparent that formal education did lend itself to successful powerlifters. As the interviewee recalled his first meet, he mentioned that “The successful powerlifters I have interacted with had a unifying trait which was their ability to problem solve. Whether it was elbow tendonitis, a food allergy, or how to execute a lift, they were always analyzing and looking for solutions”. This explanation makes sense due to the idea that college education is a rather long process for most of the people enrolled (4 years is nearly 20% of the time a typical college student has spent on this earth) and one that demands a constant ability to assess situations and determine potential solutions.  Getting stronger is no quick task and certainly not a smooth one so the ability to recognize and remedy any issue in college shares a very similar process to how one would approach solving an issue that impacts a lifter’s progression.</h5>
                            <h5 className='eduText'>
                            While not every powerlifter is a full-fledged academic there is a high level of education amongst the top performers in the two largest federations. This isn’t due to the direct correlation of formal education leading to improved lifts and a bigger total but more so the mindset a lifter utilizes. Formal education teaches individuals to be precise, observant, and mitigate potentially harmful circumstances. Also, prioritization and stress management are attributes one can obtain from academia that can improve a lifter’s quality of work. These seemingly small details make a large difference over time and can be a major contributor to the success of a powerlifter. To help people actualize their potential in the realm of powerlifting, it is apparent that education can do no harm. Education will help ensure that lifters are attentive to the details of their training, and this attention to detail will significantly help a lifter improve.  
                        </h5>
                    </Container>
                    {/* new block */}
                    <Container className='trainingBlock'>
                        <h1 className='secHead'>Importance of Bracing</h1>
                        <h4>While many injuries seem inevitable in powerlifting, there are many things you can do to prevent them. The protection of your spine is no exception and many safeguards can be taken. In order to understand how to stay safe and stable while lifting, a pop can analogy is often used. A pop can that is close is very stable when weight is applied to the top, but if the can has a leak or is open it then becomes incapable of handling load. This is in many ways comparable to your bracing. In order to protect your spine, one should attempt to create significant pressure between the ribcage and pelvis. This will give you the most stable and strongest, core possible. In order to cue this, one should attempt to push out in all directions of their abdominal region. This is a good way to begin to brace, a further understanding and analysis can be gain through kabuki strength’s explanation.
                        </h4>
                        <Link to='/kabuki' target='_blank'><h4 className='traingBlockLink'>
                        Learn more about kabuki here
                        </h4></Link>                            
                    </Container>
                    {/* new block */}
                    <Container className='trainingBlock'>
                        <h1 className='secHead'>Calculate Macros</h1>
                        <h4>
                        Macronutrients (also called macros relatively frequently) are often a topic of focus in any competitive athletic realm. Powerlifting is no exception, whether you’re a super heavyweight or a 47 kg competitor, tracking macronutrients to help aide in performance or long term goals is a necessity. Tracking macros helps to keep people honest with there food, while also quantifying calorie consumption. Calories are incredibly important for recovery as well as for losing weight. Regardless of what your desired outcome is, tracking macros will surely help you achieve it, attached below is a link for the video that I used to begin to understand macronutrients and how to track them, other videos by 3DMJ expanded on points made in the following video as well.                    </h4>
                        <Link to='/3dmj' target='_blank'><h4 className='traingBlockLink'>
                        Learn more about 3DMJ here
                        </h4></Link>                            
                    </Container>   
                    {/* new block */}
                    <Container className='trainingBlock lastOne'>
                        <h1 className='secHead'>Ankle Distraction</h1>
                        <h4>
                        When facing mobility issues in regards to your ability to perform dorsiflexion, there are a couple of approaches but the one I’ve found to be useful is banded ankle distractions. While using a band attached to your ankle and a sturdy foundation, you push your knee past your ankle creating dorsiflexion. Continuing to perform this movement multiple times will lead to it becoming more mobile at a specific point in time (following this drill), while continuing over a long period of time will result in additional mobility at all points of time. This has helped me to eliminate issues I have faced in the squat and resolved some knee pain that I had faced.
                        </h4>
                        <Link to='/ankle' target='_blank'><h4 className='traingBlockLink'>
                        Learn more about Ankle Distraction here
                        </h4></Link>                            
                    </Container>           
                </Container>
            </section>
            <Footer/>
        </div>        
        );
    }
}
    
export default Education;