

import React, {Component} from "react";
import { Link } from "react-router-dom";
import Navbar  from '../components/navbar';
import Footer  from '../components/footer';
import { Container, Row, Col, Button, Jumbotron } from 'reactstrap';
// import tempPic from '../images/p6.jpeg'

class Philosophy extends Component {  

render() {
    return (
        <div>
            <Navbar/>
           <section id='philosophy'>
                <Container id='educationCon'>
                <h1 className='blockHead'>Grit: Throughout time</h1> 
                    <Container className='trainingBlock'>
                        <h5 className='eduText'>
                        Many think the word grit is another way of saying persistence, however, that is only partially true. While in high school I encountered a teacher who used the word grit to highlight a quality of successful students, to him grit meant persistence. However, as I progressed through high school and college I wondered if that truly was what grit meant. 
                        As the popularity of the word grew and began to be used more and more in social media and other places where the gospel of success is preached, my curiosity grew to an insatiable amount. So now the question of “What does grit truly mean?” deserves an answer since it is so commonly used and has come to encompass many meanings over the years.</h5>
                        <h5 className='eduText'>                            
                        Grit has several definitions and it seems as nearly all of them are different. The Webster dictionary suggests grit is, “firmness of mind or spirit: unyielding courage in the face of hardship or danger.'' While that might be true, I find that to not be satisfactory as it is relative and leaves ambiguity. Surely not every “gritty” person is facing danger as they choose their next actions. This definition might be applicable in some settings but certainly doesn’t include most “gritty” individuals. So, to discover the truest and unadulterated meaning of the world one should turn to the study of the psychological trait that grit is.  </h5>
                        <h5 className='eduText'>
                        The current working definition posed by Angela Duckworth, the leading psychological expert in Grit, is, ‘“passion and sustained persistence applied toward long-term achievement, with no particular concern for rewards or recognition along the way.”’ This definition was concluded based on the results of the study performed by Duckworth and company. Where individuals were studied that performed exceptionally well in some of the most difficult circumstances, these difficulties are situations where failure is very prevalent and potential, therefore this definition includes physically dangerous circumstances but isn’t exclusively those situations. Certainly, persistence is represented in this definition and many others that attempt to explain grit, however, a crucial element to Duckworth’s definition is the lack of concern of recognition and the passion possessed by the individual. This is crucial because the people that exemplify grit are working for something that they value nearly above all else, their passion. Passion is something that is unquantifiable and something that Duckworth didn’t attempt to measure. However, each person studied pursued the achievement of something no matter what arose or interfered with their endeavor, they did not stray for the goal. Additionally, time is not a constraint to them. The end results justified the journey in this case. Again, when one is passionate and believes in something time is nearly irrelevant to them because they are doing what they feel compelled to do.</h5>
                        <h5 className='eduText'> 
                        As grit has evolved throughout the years, it has come to be associated with two predominant comparisons, those being success and intelligence. Grit and success go hand and hand so long as success is defined as completion of the task at hand, whatever that may be. People that exemplify grit complete the task and achieve the goal that is desired with a much higher success rate than those with less grit. However, the correlation between intelligence and grit is not a positive one. Duckworth and fellow researchers concluded that grit was either unassociated with intelligence or opposite of intelligence as shown by the following, “In four separate samples, grit was found to be either orthogonal to or slightly inversely correlated with intelligence”. This correlation is particularly interesting due to the presence of sayings such as hard work beats talent when talent refuses to work hard, due to the validity of it. This information is particularly applicable in showing people that anyone can achieve great things regardless of their IQ or other intelligence measures so long as one possesses an adequate amount of grit.</h5>
                        <h5 className='eduText'>
                        Grit is many things, but above all, it entails a person having a passion for what they’re doing. Duckworth’s explanation and studies on grit have done a phenomenal job of explaining and bringing awareness to the psychological trait that is grit. The clarity in definition allows for people that want to achieve “success” to be more aware of the characteristics and qualities they should attempt to cultivate. It brings focus to the fact that one should find their passion and embark upon developing or pursuing it. Understanding what grit is allows one to not be fooled by social media or misleading definitions of it. To be able to understand what grit is brings one closer to their goals, passions, and dreams. 
                        <h4>Works Cited</h4>
                        Angela Lee Duckworth & Patrick D. Quinn (2009) Development and Validation of the Short Grit Scale (Grit–S), Journal of Personality Assessment, 91:2, 166-174, DOI: 10.1080/00223890802634290
                        Fessler, Leah. "You're no genius": Her father's shutdowns made Angela Duckworth a world expert on grit." Quartz at Work. 28 Mar. 2018. Quartz. 23 Sept. 2019 
                        <Link to='/ankle' target='_blank'><h4 className='traingBlockLink'>
                        Read more here!
                        </h4></Link>  
                        “Grit.” Merriam-Webster, Merriam-Webster, </h5>
                    </Container>
                </Container>
            </section>
            <section id='Philosophy'>
                <Container id='educationCon'>
                    <h1 className='blockHead'> Powerlifting, the community</h1>
                    <Container className='trainingBlock'>
                        <h5 className='eduText'>
                            Life is something that is unforgiving, relentless at times and in an attempt to make the best of the situations that we find ourselves in we extend to others, looking for perspective, seeking opinions, and most of all hope that what is will subside. 
                            At a point in my life, I was looking for help and seeking validation, at the ripe age of 15 I wandered into a gym and it forever changed my life. While the gym was much of what one might expect, the people weren’t. Being the youngest person in that area came with its own set of hardships. 
                            Most people viewed me as an obstruction to their workout, mainly due to my lack of knowledge of machines and my inability to decide what I was going to be doing that day. However, one day a person gave me the time of day. 
                            His name was Luke and in that instance, both of our lives changed. While I had wandered around like a deer in headlights for the first three months of joining the gym, Luke revolutionized my training that day.</h5>
                            <h5 className='eduText'>
                            That day, Luke sat with me and gave me a condensed rendition of lifting, helped me put together a plan for how I’d lift in the future. More than that, however, Luke extended a hand by asking me to lift with him in the future, and while the proposition frightened me, I ultimately did. Lifting with a man who was medically discharged for the army, but had the stubbornness to will himself to a 700 lb deadlift on a bad knee is a different kind of intimidation. I saw a man who was able to endure what life had thrown his way but in a miraculous effort, not only handle what was hurled towards him but make the best of each situation which was truly inspiring.</h5>
                            <h5 className='eduText'>
                            Training with Luke improved over time, I gained confidence and started training seriously with him four times a week. A day I will never forget was when I attempted to deadlift 500 lbs. We had discussed this attempt days prior to it and it was truly something I feared. 500 lbs was a threshold that I thought strong people were defined by, and I didn’t believe myself to be strong. So as I entered the gym that day, we sat and talked as we always did before a lift and Luke said something I carry with me to this day, he said “It doesn’t matter what you accomplish, so long as you have given it your all. Regardless of the win and loss column, if you can look yourself in the mirror and admit that you gave it your all, then nothing more can be asked of you”. So as I approached the bar that day, I had a sense of clarity, that the validation I had been seeking for so long prior was actually something I could bring myself, so long as I gave every endeavor my 100% effort. That day I went on to pull 500 lbs for the first time, and I was able to realize I was strong and always had been. It had nothing to do with the weight but everything between the ears. The entire time I had the capacity to resolve my issues, but I looked everywhere but to myself. I left the gym that day with a perspective that catalyzed much of my progress and success. I went on to pursue powerlifting and academics to the best of my capability.</h5>
                            <h5 className='eduText'>
                            This acquired self-belief that I had doesn’t seem particularly unique amongst powerlifters. The community is small and tightly knit. Often times powerlifting is 10% physical and 90% mental. Reading training logs of many of the top lifters most powerlifters didn’t just elect to lift weights, they had an experience that meant something so profound to them. Dave Tate was an accomplished lifter but was far from his potential, luckily for him he had one of the best powerlifting coaches in the world and a great training group. However, that circumstance will force growth and strength progress, but to be an all-time world record holder, one must also have self-belief. During a competition where Dave Tate was poised to break a personal record on his squat, Louie Simmons (the coach) said, “It’s going to feel heavy but that doesn’t mean you can’t do it” (Tate 2019). This instance meant more than anyone realized. This was the beginning of Dave Tate’s journey to break multiple world records but also create a multimillion-dollar business that is one of the leading powerlifting equipment suppliers. In addition to all this, Dave Tate has contributed thousands of hours of video, seminars, coaching, and advice to the powerlifting community all while embodying the phrase, “Live. Learn. Pass on”. Dave is a great example of what powerlifting can lead to once one has the soundness of mind to believe in themself.</h5>
                            <h5 className='eduText'>
                            While Dave is an anomaly, as not everyone is fit to break world records, it seems that regardless of what weight one lifts, there was a realization in every experience. A realization that no matter what the circumstances are each person has the ability to see it through, persevere and eventually overcoming adversity. In doing so, you’ll have to come to grips with the things that you typically are most fearful of.  I know people who have torn quadriceps off the bone, blown biceps off, and ruptured vertebrae. Injury is by far the hardest lifting related thing to deal with. Coming back from that is very hard and some don’t, Joe Sullivan, an elite level powerlifter has said, “It’s easier to die with passion than to live with it” and injury gives you a way out so to speak. Having spoken with a friend that had suffered an injury that put him out of powerlifting for six months he explained that it was extremely hard and went on to explain some of the struggles he’s dealt with, “While I was recovering from surgery I thought the hardest part  would not being able to lift, but honestly I miss the community more than anything”. In a further conversation that I have had with Austin, he made it apparent that the fulfillment he got from giving back to powerlifters and people in the gym is the most fulfilling thing he has done in this realm. The injury was extremely hard on Austin as his 500 lb deadlift dwindled 
                            to maybe a 315 lb lift, but most of all Austin has expressed he wants to give back and help people that found themselves to be in his position. While the set back wasn’t what he wanted, it gave him a unique perspective and made it obvious of what he ultimately wants to do with his powerlifting career, having told me, “I’d rather be remembered for who I am and who I helped instead of what I lifted”. Battling through injury has defined what he wants going forward, and created a significant purpose in his life, to help and aid others in becoming strong, functional, and well-rounded beings. Powerlifting brings experiences and lessons in odd ways, but they’re always there.</h5>
                            <h5 className='eduText'>
                            I found myself in South Bend, Indiana on a warm summer day to participate in a charity push-pull meet. I had decided to drive down a couple of days prior in order to help fundraise for Mia, a 4-year-old girl who was battling a failing organ and needed a transplant in the coming weeks. I, along with hundreds of other lifters piled into East Race Muscle to test or maxes for bench press and deadlift, but we all knew the magnitude of the situation. See it wasn’t about lifting that day, it was about the community of lifters. Mia was running around all-day bringing smiles to people’s faces while here dad, Baxter, facilitated the event. Baxter had been battling the fact that so much could go wrong with the operation, the inherent risk of the operation, not to mention the possible rejection of the organ. So while Baxter knew hard times had found him, he invited the people that he thought would help the situation. While I was new to this experience, I saw how Joe Sullivan, Garrett Fear, Julius Maddox, and others (these are all world record holders or the best in the world in their class) treated Baxter and supported him. So when Joe stepped up to pull his final deadlift of 700 lbs with a hand that was torn across his entire palm it only seemed right. See your not supposed to be able to deadlift with a cut that runs across your entire hand, your not supposed to try three times on a weight that should’ve moved 
                            easily, you’re not supposed to be stubborn enough to believe the third time would be different than the first, but he believed and we did as well. As we crowded the platform and yelled and screamed in support, Baxter’s mom said words that brought chills over the crowd, she said, “This is how it is supposed to be” and it couldn’t have been truer. Joe successfully pulled that 700 lbs but more importantly Joe overcame adversity. Joe instilled a little hope and faith in everyone there, especially Baxter. I saw how this community cared for one of their own, I saw how it gave everything it could to help Baxter while he faced the hardest time in his life. So while powerlifting is measured by how well you can squat, bench, and deadlift, the true goal is to give back and leave the community better than you found it. Joe gave everything he could give that day and inspired many, including myself. So as time passes, I hope to make a constant contribution through writing, helping others, and offering knowledge and perspective. Powerlifting won’t give you what you want, It’ll give you what you need: a reason to believe, purpose, structure, knowledge.
                        </h5>
                    </Container>
                </Container>
            </section>
            <Footer/>
        </div>        
        );
    }
}
    
export default Philosophy;